
@@OKTbls_0.sql

prompt # перенос из темповых таблиц в публичные

insert into OK_ACADEMIC(ID,BRANCH,PERSONAL_CODE,ACADEMIC_CODE,ACADEMIC_DATE,EMP_CODE,INS_DATE,STATE) select ID,BRANCH,PERSONAL_CODE,ACADEMIC_CODE,ACADEMIC_DATE,EMP_CODE,INS_DATE,STATE from OK_ACADEMIC_temp; 
commit;

insert into OK_ADDINFORM(ID,BRANCH,PERSONAL_CODE,ADDINFORM_DATE,CHARACTER_ADDINFORM,EMP_CODE,INS_DATE) select ID,BRANCH,PERSONAL_CODE,ADDINFORM_DATE,CHARACTER_ADDINFORM,EMP_CODE,INS_DATE from OK_ADDINFORM_temp; 
commit;


insert into OK_ARMY(ID,BRANCH,PERSONAL_CODE,ARMY_CODE,FITNESS_ARMY_CODE,
 SPECIAL_ARMY, NUMBER_VUS,CODE_ARMY_POST,NAME_ARMY_OFFICE,
SPECREG_NUMBER,EMP_CODE,INS_DATE,ARMY_GROUP_CODE,CATEGORY_ARMY_CODE,MILITARY_RANK_CODE,
STAFF_CODE,TYPE_FORCE_CODE) select ID,BRANCH,PERSONAL_CODE,ARMY_CODE,FITNESS_ARMY_CODE,
   SPECIAL_ARMY, NUMBER_VUS,CODE_ARMY_POST,
NAME_ARMY_OFFICE,SPECREG_NUMBER,EMP_CODE,INS_DATE,ARMY_GROUP_CODE,CATEGORY_ARMY_CODE,MILITARY_RANK_CODE,
STAFF_CODE,TYPE_FORCE_CODE from OK_ARMY_TEMP; 
commit;


insert into OK_ATTESTATION(ID,BRANCH,PERSONAL_CODE,DATE_ATTESTATION,NUM_ATTESTATION,EMP_CODE,INS_DATE) select ID,BRANCH,PERSONAL_CODE,DATE_ATTESTATION,NUM_ATTESTATION,EMP_CODE,INS_DATE from OK_ATTESTATION_temp; 
commit;

insert into OK_AWARD(ID,BRANCH,PERSONAL_CODE,AWARD_DATE,AWARD_INFO,EMP_CODE,INS_DATE,AWARD_DATE_MM,AWARD_DATE_DD) select ID,BRANCH,PERSONAL_CODE,AWARD_DATE,AWARD_INFO,EMP_CODE,INS_DATE,AWARD_DATE_MM,AWARD_DATE_DD from OK_AWARD_temp; 
commit;

insert into OK_BUSINESS_VOYAGE(BRANCH,PERSONAL_CODE,KV_KURS_CODE,DATE_OPEN,DATE_CLOSE,NUMBER_DAY,ORG_BUSINESS_VOYAGE_CODE,THEME_BUSINESS_VOYAGE_CODE,CODE_STR,ORDER_NUM,ORDER_DATE,PRIM,EMP_CODE,INS_DATE,CITY_CODE) select BRANCH,PERSONAL_CODE,KV_KURS_CODE,DATE_OPEN,DATE_CLOSE,NUMBER_DAY,ORG_BUSINESS_VOYAGE_CODE,THEME_BUSINESS_VOYAGE_CODE,CODE_STR,ORDER_NUM,ORDER_DATE,PRIM,EMP_CODE,INS_DATE,CITY_CODE from OK_BUSINESS_VOYAGE_temp; 
commit;

insert into OK_CHANGE_FIO(ID,BRANCH,PERSONAL_CODE,FAMILY,FIRST_NAME,PATRONYMIC,CHANGE_DATE,CHANGE_MOTIVE,EMP_CODE,INS_DATE) select ID,BRANCH,PERSONAL_CODE,FAMILY,FIRST_NAME,PATRONYMIC,CHANGE_DATE,CHANGE_MOTIVE,EMP_CODE,INS_DATE from OK_CHANGE_FIO_temp; 
commit;

insert into OK_CONVICTIONS(ID,BRANCH,PERSONAL_CODE,CONVICTIONS_DATE,CONVICTIONS_MOTIVE,EMP_CODE,INS_DATE) select ID,BRANCH,PERSONAL_CODE,CONVICTIONS_DATE,CONVICTIONS_MOTIVE,EMP_CODE,INS_DATE from OK_CONVICTIONS_temp; 
commit;

insert into OK_DEGREE(ID,BRANCH,PERSONAL_CODE,DEGREE_CODE,DEGREE_DATE,EMP_CODE,INS_DATE,STATE) select ID,BRANCH,PERSONAL_CODE,DEGREE_CODE,DEGREE_DATE,EMP_CODE,INS_DATE,STATE from OK_DEGREE_temp; 
commit;

insert into OK_EDUCATION(ID,BRANCH,PERSONAL_CODE,EDUCATION_CODE,BASIS_CODE,INSTITUTION_CODE,BEGIN_DATE,END_DATE,PROFESSION_PERSONAL,QUALIFICATION_CODE,DIPLOM_NUM,EMP_CODE,INS_DATE,COD_VUZ_PRIM,CURS,FAKULTET,NOSTRA,NOSTRA_SERIES,NOSTRA_NUMBER,NOSTRA_DATE,DIPLOM_DATE,BEGIN_DATE_MM,BEGIN_DATE_DD,END_DATE_MM,END_DATE_DD) select ID,BRANCH,PERSONAL_CODE,EDUCATION_CODE,BASIS_CODE,INSTITUTION_CODE,BEGIN_DATE,END_DATE,PROFESSION_PERSONAL,QUALIFICATION_CODE,DIPLOM_NUM,EMP_CODE,INS_DATE,COD_VUZ_PRIM,CURS,FAKULTET,NOSTRA,NOSTRA_SERIES,NOSTRA_NUMBER,NOSTRA_DATE,DIPLOM_DATE,BEGIN_DATE_MM,BEGIN_DATE_DD,END_DATE_MM,END_DATE_DD from OK_EDUCATION_temp; 
commit;

insert into OK_ELECTION(ID,BRANCH,PERSONAL_CODE,ELECTION_ADDRESS,ELECTION_NAME,ELECTION_POST,ELECTION_DATE_BEGIN,ELECTION_DATE_END,EMP_CODE,INS_DATE,ELECTION_CODE,ELECTION_DATE_BEGIN_MM,ELECTION_DATE_BEGIN_DD,ELECTION_DATE_END_MM,ELECTION_DATE_END_DD) select ID,BRANCH,PERSONAL_CODE,ELECTION_ADDRESS,ELECTION_NAME,ELECTION_POST,ELECTION_DATE_BEGIN,ELECTION_DATE_END,EMP_CODE,INS_DATE,ELECTION_CODE,ELECTION_DATE_BEGIN_MM,ELECTION_DATE_BEGIN_DD,ELECTION_DATE_END_MM,ELECTION_DATE_END_DD from OK_ELECTION_temp; 
commit;

insert into OK_HOSPITAL(BRANCH,PERSONAL_CODE,HOSPITAL_CODE,HOSPITAL_DOC,DATE_OPEN,DATE_CLOSE,NUMBER_DAY,WORK_PERIOD,PERCENTAGE,DIAGNOSIS,DATE_HOSPITAL,PRIM_HOSPITAL,SHIFR,PRIM,EMP_CODE,INS_DATE) select BRANCH,PERSONAL_CODE,HOSPITAL_CODE,HOSPITAL_DOC,DATE_OPEN,DATE_CLOSE,NUMBER_DAY,WORK_PERIOD,PERCENTAGE,DIAGNOSIS,DATE_HOSPITAL,PRIM_HOSPITAL,SHIFR,PRIM,EMP_CODE,INS_DATE from OK_HOSPITAL_temp; 
commit;

insert into OK_INCREASE(BRANCH,PERSONAL_CODE,INCREASE_CODE,INCREASE_VIEW,INCREASE_PERCENTAGE,RAZN,DATE_OPEN,DATE_CLOSE,EMP_CODE,INS_DATE) select BRANCH,PERSONAL_CODE,INCREASE_CODE,INCREASE_VIEW,INCREASE_PERCENTAGE,RAZN,DATE_OPEN,DATE_CLOSE,EMP_CODE,INS_DATE from OK_INCREASE_temp; 
commit;

insert into OK_KURS(BRANCH,PERSONAL_CODE,FIO,KV_KURS_CODE,EMP_CODE,INS_DATE) select BRANCH,PERSONAL_CODE,FIO,KV_KURS_CODE,EMP_CODE,INS_DATE from OK_KURS_temp; 
commit;

insert into OK_LANGUAGE(ID,BRANCH,PERSONAL_CODE,LANGUAGE_CODE,LEVEL_CODE,EMP_CODE,INS_DATE,STATE,COD_LANG_PRIM) select ID,BRANCH,PERSONAL_CODE,LANGUAGE_CODE,LEVEL_CODE,EMP_CODE,INS_DATE,STATE,COD_LANG_PRIM from OK_LANGUAGE_temp; 
commit;

insert into OK_LEAVE(ID,BRANCH,PERSONAL_CODE,LEAVE_CODE,BEGIN_YEAR,END_YEAR,PERIOD_LEAVE,DATE_IN_LEAVE,DATE_OUT_LEAVE,MOTIVE_LEAVE,NUM_BASIS,DATE_BASIS,EMP_CODE,INS_DATE,DATE_RECALL_BEGIN,DATE_RECALL_END,DATE_ORDER_RECALL,NUM_ORDER_RECALL,PRIM,PERIOD_LEAVE_RECALL) select ID,BRANCH,PERSONAL_CODE,LEAVE_CODE,BEGIN_YEAR,END_YEAR,PERIOD_LEAVE,DATE_IN_LEAVE,DATE_OUT_LEAVE,MOTIVE_LEAVE,NUM_BASIS,DATE_BASIS,EMP_CODE,INS_DATE,DATE_RECALL_BEGIN,DATE_RECALL_END,DATE_ORDER_RECALL,NUM_ORDER_RECALL,PRIM,PERIOD_LEAVE_RECALL from OK_LEAVE_temp; 
commit;


insert into OK_PARTY(ID,BRANCH,PERSONAL_CODE,PARTY_CODE,OUT_PARTY,PARTY_DATE,PARTY_OUTDATE,PUNISHMENT_MOTIVE,PUNISHMENT_DATE,EMP_CODE,INS_DATE,CODE_PARTII_PRIM) select ID,BRANCH,PERSONAL_CODE,PARTY_CODE,OUT_PARTY,PARTY_DATE,PARTY_OUTDATE,PUNISHMENT_MOTIVE,PUNISHMENT_DATE,EMP_CODE,INS_DATE,CODE_PARTII_PRIM from OK_PARTY_temp; 
commit;

insert into OK_PENALTY(ID,BRANCH,PERSONAL_CODE,PENALTY_CODE,PENALTY_MOTIVE,PENALTY_DATE,PENALTY_NUM,EMP_CODE,INS_DATE) select ID,BRANCH,PERSONAL_CODE,PENALTY_CODE,PENALTY_MOTIVE,PENALTY_DATE,PENALTY_NUM,EMP_CODE,INS_DATE from OK_PENALTY_temp; 
commit;


insert into OK_PERIOD(ID,BRANCH,PERSONAL_CODE,IN_OFFICE_DATE,OUT_OFFICE_DATE,OFFICE_NAME,OFFICE_ADDRESS,ESTABLISHED_POST,
TYPE_PERIOD_CODE,ARTICLE_CODE,BASIS_NUM,BASIS_DATE,EMP_CODE,INS_DATE,BASE_MOVE_CODE,
ESTABLISHED_DEPARTMENT,PRIZ_SYSTEM,COD_BANK,COD_TYPE_PRN,COD_PR_OFF,PR_OFF,DATE_UTV_KM,NUMB_UTV_KM,
DATE_PR_KVL,NUMB_PR_KVL,DATE_ATTEST,RESH_ATTEST,DOLJN_ID,NUM_PR_OFF,DATE_PR_OFF,POST_CODE,DEPARTMENT_CODE) select ID,
BRANCH,PERSONAL_CODE,IN_OFFICE_DATE,OUT_OFFICE_DATE,OFFICE_NAME,OFFICE_ADDRESS,ESTABLISHED_POST,
TYPE_PERIOD_CODE,ARTICLE_CODE,BASIS_NUM,BASIS_DATE,EMP_CODE,INS_DATE,BASE_MOVE_CODE,ESTABLISHED_DEPARTMENT,PRIZ_SYSTEM,COD_BANK,COD_TYPE_PRN,COD_PR_OFF,PR_OFF,DATE_UTV_KM,NUMB_UTV_KM,DATE_PR_KVL,NUMB_PR_KVL,DATE_ATTEST,RESH_ATTEST,DOLJN_ID,NUM_PR_OFF,DATE_PR_OFF,POST_CODE,DEPARTMENT_CODE from OK_PERIOD_temp; 
commit;


insert into OK_PERSONAL(ID,BRANCH,PERSONAL_CODE,COLLEAGUE_CODE,STATUS_CODE,SALARY_CODE,FAMILY,FIRST_NAME,PATRONYMIC,GENDER_CODE,BIRTHDAY,REGION_ID,DISTR,NATIONALITY_CODE,FAMILY_STATUS_CODE,REG_TYPE_CODE,HOME_ADDRESS,HOME_ADDRESSFACT,PASS_SERIYA,PASS_NUM,PASS_DATE,PASS_REG,RECORD_BOOK_NUMBER,RECORD_BOOK_SERIES,TELEFON,EMP_CODE,INS_DATE,PROFMEMBER,TABNO,EDUCATION_TITLE_CODE,BIRTHPLACE,MOTIVE_OUT,BASIS_NUM,BASIS_DATE,LEAVE_CODE,DEPARTMENT_CODE,POST_CODE,NN,MOTIVE_DISMISSIAL_CODE,NPS_ID,SPECIAL_CODE,INN,COD_DISTR_UVD,COD_DISTR_PRIM,COD_STR_BIRTH,COD_OBL_PRIM,COD_PLACE_BIRTH_PRIM,COD_SITIZENT,COD_STR_SITIZENT,COD_STR_LIVE,COD_OBL_LIVE,COD_OBL_LIVE_PRIM,COD_DISTR_LIVE,COD_DISTR_LIVE_PRIM,CODE_NACI_PRIM,CHECK_KFS,IS_BOSS,BANK_SPEC,NOTICE,PRICH_ID,NAME_PR,SROK_DATE,HOME_ADDRESSFACT_REGION_ID,HOME_ADDRESSFACT_DISTR,HOME_ADDRESS_REGION_ID,HOME_ADDRESS_DISTR,PASSPORT_TYPE_CODE,REGPLACE_CODE,PASS_DATE_END,GOSUBMIT_CODE) select ID,BRANCH,PERSONAL_CODE,COLLEAGUE_CODE,STATUS_CODE,SALARY_CODE,FAMILY,FIRST_NAME,PATRONYMIC,GENDER_CODE,BIRTHDAY,REGION_ID,DISTR,NATIONALITY_CODE,FAMILY_STATUS_CODE,REG_TYPE_CODE,HOME_ADDRESS,HOME_ADDRESSFACT,PASS_SERIYA,PASS_NUM,PASS_DATE,PASS_REG,RECORD_BOOK_NUMBER,RECORD_BOOK_SERIES,TELEFON,EMP_CODE,INS_DATE,PROFMEMBER,TABNO,EDUCATION_TITLE_CODE,BIRTHPLACE,MOTIVE_OUT,BASIS_NUM,BASIS_DATE,LEAVE_CODE,DEPARTMENT_CODE,POST_CODE,NN,MOTIVE_DISMISSIAL_CODE,NPS_ID,SPECIAL_CODE,INN,COD_DISTR_UVD,COD_DISTR_PRIM,COD_STR_BIRTH,COD_OBL_PRIM,COD_PLACE_BIRTH_PRIM,COD_SITIZENT,COD_STR_SITIZENT,COD_STR_LIVE,COD_OBL_LIVE,COD_OBL_LIVE_PRIM,COD_DISTR_LIVE,COD_DISTR_LIVE_PRIM,CODE_NACI_PRIM,CHECK_KFS,IS_BOSS,BANK_SPEC,NOTICE,PRICH_ID,NAME_PR,SROK_DATE,HOME_ADDRESSFACT_REGION_ID,HOME_ADDRESSFACT_DISTR,HOME_ADDRESS_REGION_ID,HOME_ADDRESS_DISTR,PASSPORT_TYPE_CODE,REGPLACE_CODE,PASS_DATE_END,GOSUBMIT_CODE from OK_PERSONAL_temp; 
commit;

insert into OK_POST(ID,BRANCH,PERSONAL_CODE,APPOINTMENT_DATE,APPOINTMENT_MOTIVE,DEPARTMENT_CODE,POST_CODE,GRADE,SALARY_FACT,RAISE_PERSONAL,RAISE_ADD,BASIS_NUM,BASIS_DATE,EMP_CODE,INS_DATE,STATE,BASE_MOVE_CODE) select ID,BRANCH,PERSONAL_CODE,APPOINTMENT_DATE,APPOINTMENT_MOTIVE,DEPARTMENT_CODE,POST_CODE,GRADE,SALARY_FACT,RAISE_PERSONAL,RAISE_ADD,BASIS_NUM,BASIS_DATE,EMP_CODE,INS_DATE,STATE,BASE_MOVE_CODE from OK_POST_temp; 
commit;

insert into OK_PREMIUM(ID,BRANCH,PERSONAL_CODE,PREMIUM_DATE,PREMIUM_NAME,EMP_CODE,INS_DATE) select ID,BRANCH,PERSONAL_CODE,PREMIUM_DATE,PREMIUM_NAME,EMP_CODE,INS_DATE from OK_PREMIUM_temp; 
commit;

insert into OK_PRIVILEGE(BRANCH,PERSONAL_CODE,PRIVILEGE_CODE,PRIVILEGE_DOC,DATE_OPEN,DATE_CLOSE,PRIM,EMP_CODE,INS_DATE) select BRANCH,PERSONAL_CODE,PRIVILEGE_CODE,PRIVILEGE_DOC,DATE_OPEN,DATE_CLOSE,PRIM,EMP_CODE,INS_DATE from OK_PRIVILEGE_temp; 
commit;

insert into OK_RELATION(ID,BRANCH,PERSONAL_CODE,RELATION_CODE,RELATION_FAMILY,RELATION_NAME,RELATION_PATRONYMIC,RELATION_BIRTHDAY,RELATION_BIRTHPLACE,RELATION_OFFICE,RELATION_POST,RELATION_HOME_ADDRESS,EMP_CODE,INS_DATE,RELATION_DEATHDAY,COD_STR_LIVE,COD_OBL_LIVE,COD_OBL_LIVE_PRIM,COD_CITY,COD_CITY_PRIM,COD_STR_LIVE_PRIM,COD_STR_BIRTH,COD_STR_BIRTH_PRIM,COD_OBL_BIRTH,COD_OBL_BIRTH_PRIM,COD_CITY_BIRTH,COD_CITY_BIRTH_PRIM,DD,MM,DD_DEATH,MM_DEATH) select ID,BRANCH,PERSONAL_CODE,RELATION_CODE,RELATION_FAMILY,RELATION_NAME,RELATION_PATRONYMIC,RELATION_BIRTHDAY,RELATION_BIRTHPLACE,RELATION_OFFICE,RELATION_POST,RELATION_HOME_ADDRESS,EMP_CODE,INS_DATE,RELATION_DEATHDAY,COD_STR_LIVE,COD_OBL_LIVE,COD_OBL_LIVE_PRIM,COD_CITY,COD_CITY_PRIM,COD_STR_LIVE_PRIM,COD_STR_BIRTH,COD_STR_BIRTH_PRIM,COD_OBL_BIRTH,COD_OBL_BIRTH_PRIM,COD_CITY_BIRTH,COD_CITY_BIRTH_PRIM,DD,MM,DD_DEATH,MM_DEATH from OK_RELATION_temp; 
commit;

insert into OK_REZERV(MASTER_ID,BRANCH,BRANCH_SHOW,DEPARTMENT_CODE,POST_CODE,PERSONAL_CODE,EMP_CODE,INS_DATE) select MASTER_ID,BRANCH,BRANCH_SHOW,DEPARTMENT_CODE,POST_CODE,PERSONAL_CODE,EMP_CODE,INS_DATE from OK_REZERV_temp; 
commit;

insert into OK_REZERV_DETAIL(ID,MASTER_ID,BRANCH,BRANCH_SHOW,DEPARTMENT_CODE,POST_CODE,FAMILY,FIRST_NAME,PATRONYMIC,EMP_CODE,INS_DATE) select ID,MASTER_ID,BRANCH,BRANCH_SHOW,DEPARTMENT_CODE,POST_CODE,FAMILY,FIRST_NAME,PATRONYMIC,EMP_CODE,INS_DATE from OK_REZERV_DETAIL_temp; 
commit;

insert into OK_RISE(ID,BRANCH,PERSONAL_CODE,RISE_DATE_YEAR,RISE_INFO,EMP_CODE,INS_DATE,RISE_DATE_MM,RISE_DATE_DD) select ID,BRANCH,PERSONAL_CODE,RISE_DATE_YEAR,RISE_INFO,EMP_CODE,INS_DATE,RISE_DATE_MM,RISE_DATE_DD from OK_RISE_temp; 
commit;

insert into OK_SCIENTIFIC(ID,BRANCH,PERSONAL_CODE,SCIENTIFIC_INFO,SCIENTIFIC_DATE,EMP_CODE,INS_DATE) select ID,BRANCH,PERSONAL_CODE,SCIENTIFIC_INFO,SCIENTIFIC_DATE,EMP_CODE,INS_DATE from OK_SCIENTIFIC_temp; 
commit;

insert into OK_STAT(ID,BRANCH,STAT_CODE,DEPARTMENT_CODE,POST_CODE,QUANTITY_POST,SALARY_FACT,EMP_CODE,INS_DATE,SPECIAL_CODE) select ID,BRANCH,STAT_CODE,DEPARTMENT_CODE,POST_CODE,QUANTITY_POST,SALARY_FACT,EMP_CODE,INS_DATE,SPECIAL_CODE from OK_STAT_temp; 
commit;

insert into OK_STAT_SALARY(ID,BRANCH,SALARY_CODE,STAT_CODE,VACANCY_CODE,VACANCY_DATE,REZERVE_CODE,EMP_CODE,INS_DATE) select ID,BRANCH,SALARY_CODE,STAT_CODE,VACANCY_CODE,VACANCY_DATE,REZERVE_CODE,EMP_CODE,INS_DATE from OK_STAT_SALARY_temp; 
commit;

insert into OK_TABEL(BRANCH,TABEL_MONTH,TABEL_YEAR,TABEL_NAME,PERSONAL_CODE,NN,DEPARTMENT_NN,DEPARTMENT_CODE,DEPARTMENT_NAME,FIO,TABNO,SALARY,POST_CODE,POST_NAME,WORK_DAYS,WORK_HOURS,WORK_HOLIDAYS,DEKRET_DAYS,BUSINESS_TOUR_DAYS,ILL_DAYS,VACATION_DAYS,EDUCATIONAL_VACATION_DAYS,NOSALARY_VACATION_DAYS,DAY01,DAY02,DAY03,DAY04,DAY05,DAY06,DAY07,DAY08,DAY09,DAY10,DAY11,DAY12,DAY13,DAY14,DAY15,DAY16,DAY17,DAY18,DAY19,DAY20,DAY21,DAY22,DAY23,DAY24,DAY25,DAY26,DAY27,DAY28,DAY29,DAY30,DAY31,EMP_CODE,INS_DATE,OLDDAY01,OLDDAY02,OLDDAY03,OLDDAY04,OLDDAY05,OLDDAY06,OLDDAY07,OLDDAY08,OLDDAY09,OLDDAY10,OLDDAY11,OLDDAY12,OLDDAY13,OLDDAY14,OLDDAY15,OLDDAY16,OLDDAY17,OLDDAY18,OLDDAY19,OLDDAY20,OLDDAY21,OLDDAY22,OLDDAY23,OLDDAY24,OLDDAY25,OLDDAY26,OLDDAY27,OLDDAY28,OLDDAY29,OLDDAY30,OLDDAY31,CATEGORY_CODE) select BRANCH,TABEL_MONTH,TABEL_YEAR,TABEL_NAME,PERSONAL_CODE,NN,DEPARTMENT_NN,DEPARTMENT_CODE,DEPARTMENT_NAME,FIO,TABNO,SALARY,POST_CODE,POST_NAME,WORK_DAYS,WORK_HOURS,WORK_HOLIDAYS,DEKRET_DAYS,BUSINESS_TOUR_DAYS,ILL_DAYS,VACATION_DAYS,EDUCATIONAL_VACATION_DAYS,NOSALARY_VACATION_DAYS,DAY01,DAY02,DAY03,DAY04,DAY05,DAY06,DAY07,DAY08,DAY09,DAY10,DAY11,DAY12,DAY13,DAY14,DAY15,DAY16,DAY17,DAY18,DAY19,DAY20,DAY21,DAY22,DAY23,DAY24,DAY25,DAY26,DAY27,DAY28,DAY29,DAY30,DAY31,EMP_CODE,INS_DATE,OLDDAY01,OLDDAY02,OLDDAY03,OLDDAY04,OLDDAY05,OLDDAY06,OLDDAY07,OLDDAY08,OLDDAY09,OLDDAY10,OLDDAY11,OLDDAY12,OLDDAY13,OLDDAY14,OLDDAY15,OLDDAY16,OLDDAY17,OLDDAY18,OLDDAY19,OLDDAY20,OLDDAY21,OLDDAY22,OLDDAY23,OLDDAY24,OLDDAY25,OLDDAY26,OLDDAY27,OLDDAY28,OLDDAY29,OLDDAY30,OLDDAY31,CATEGORY_CODE from OK_TABEL_temp; 
commit;

insert into OK_VOYAGE(ID,BRANCH,PERSONAL_CODE,VOYAGE_DATE,VOYAGE_LAND,VOYAGE_INFO,EMP_CODE,INS_DATE,VOYAGE_STR,DATA_IN,VOYAGE_DATE_MM,VOYAGE_DATE_DD,DATA_IN_MM,DATA_IN_DD) select ID,BRANCH,PERSONAL_CODE,VOYAGE_DATE,VOYAGE_LAND,VOYAGE_INFO,EMP_CODE,INS_DATE,VOYAGE_STR,DATA_IN,VOYAGE_DATE_MM,VOYAGE_DATE_DD,DATA_IN_MM,DATA_IN_DD from OK_VOYAGE_temp; 
commit;

insert into OK_YOUTH(ID,BRANCH,PERSONAL_CODE,YOUTH_CODE,IN_DATE,OUT_DATE,EMP_CODE,INS_DATE) select ID,BRANCH,PERSONAL_CODE,YOUTH_CODE,IN_DATE,OUT_DATE,EMP_CODE,INS_DATE from OK_YOUTH_temp; 
commit;

insert into OK_ZP_RATE(BRANCH,PERSONAL_CODE,ZP_RATE_CODE,ZP_RATE_TYPE_CODE,ZP_RATE_ORDER_NUM,ZP_RATE_ORDER_DATE,ZP_RATE_DATE,ZP_FAKT,EMP_CODE,INS_DATE,ZP_RATE_DATE_END) select BRANCH,PERSONAL_CODE,ZP_RATE_CODE,ZP_RATE_TYPE_CODE,ZP_RATE_ORDER_NUM,ZP_RATE_ORDER_DATE,ZP_RATE_DATE,ZP_FAKT,EMP_CODE,INS_DATE,ZP_RATE_DATE_END from OK_ZP_RATE_temp; 
commit;

