spool c:\err.txt
--на всех кроме главного мфо !!!

drop public synonym SS_OK; 
drop public synonym SS_OK_ACADEMIC;
drop public synonym SS_OK_ARMY;
drop public synonym SS_OK_ARMY_GROUP;
drop public synonym SS_OK_ARTICLE; 
drop public synonym SS_OK_BASE_MOVE; 
drop public synonym SS_OK_BASIS; 
drop public synonym SS_OK_CATEGORY;
drop public synonym SS_OK_CATEGORY_ARMY; 
drop public synonym SS_OK_CITY;
drop public synonym SS_OK_COMMAND_PARAM; 
drop public synonym SS_OK_COMMAND_TYPE;
drop public synonym SS_OK_DEGREE;
drop public synonym SS_OK_DEPARTMENT;
drop public synonym SS_OK_DEPARTMENT_TYPE; 
drop public synonym SS_OK_DISTR; 
drop public synonym SS_OK_EDUCATION; 
drop public synonym SS_OK_EDUCATION_TITLE; 
drop public synonym SS_OK_ELECTION;
drop public synonym SS_OK_FAMILY_STATUS; 
drop public synonym SS_OK_FITNESS_ARMY;
drop public synonym SS_OK_GENDER;
drop public synonym SS_OK_HOSPITAL;
drop public synonym SS_OK_INCREASE;
drop public synonym SS_OK_INSTITUTION; 
drop public synonym SS_OK_KV_KURS; 
drop public synonym SS_OK_LANGUAGE;
drop public synonym SS_OK_LEAVE; 
drop public synonym SS_OK_LEVEL_BOSS;
drop public synonym SS_OK_LEVEL_DEPARTMENT;
drop public synonym SS_OK_LEVEL_LANGUAGE;
drop public synonym SS_OK_MILITARY_RANK; 
drop public synonym SS_OK_MIN_ZP;
drop public synonym SS_OK_MOTIVE_DISMISSIAL; 
drop public synonym SS_OK_NATIONALITY; 
drop public synonym SS_OK_NCI; 
drop public synonym SS_OK_ORG_BUSINESS_VOYAGE; 
drop public synonym SS_OK_PARTY; 
drop public synonym SS_OK_PASSPORT_TYPE; 
drop public synonym SS_OK_PENALTY; 
drop public synonym SS_OK_PERS_COL_DFLT; 
drop public synonym SS_OK_PERS_QUERY;
drop public synonym SS_OK_PERS_QUERY_COL;
drop public synonym SS_OK_POST;
drop public synonym SS_OK_PRIVILEGE; 
drop public synonym SS_OK_PROFMEMBER;
drop public synonym SS_OK_QUALIFICATION; 
drop public synonym SS_OK_REGION;
drop public synonym SS_OK_REGPLACE;
drop public synonym SS_OK_REG_TYPE;
drop public synonym SS_OK_RELATION;
drop public synonym SS_OK_REZERV;
drop public synonym SS_OK_REZERVE; 
drop public synonym SS_OK_SPECIAL; 
drop public synonym SS_OK_STAFF; 
drop public synonym SS_OK_STATUS;
drop public synonym SS_OK_STR; 
drop public synonym SS_OK_TEMPLATE_COMMAND;
drop public synonym SS_OK_THEME_BUSINESS_VOYAGE; 
drop public synonym SS_OK_TYPE_FORCE;
drop public synonym SS_OK_TYPE_PERIOD; 
drop public synonym SS_OK_VACANCY; 
drop public synonym SS_OK_YOUTH; 
drop public synonym SS_OK_ZP_RATE; 
drop public synonym SS_OK_ZP_RATE_TYPE;

--на всех кроме главного мфо !!!

drop table SS_OK; 
drop table SS_OK_ACADEMIC;
drop table SS_OK_ARMY;
drop table SS_OK_ARMY_GROUP;
drop table SS_OK_ARTICLE; 
drop table SS_OK_BASE_MOVE; 
drop table SS_OK_BASIS; 
drop table SS_OK_CATEGORY;
drop table SS_OK_CATEGORY_ARMY; 
drop table SS_OK_CITY;
drop table SS_OK_COMMAND_PARAM; 
drop table SS_OK_COMMAND_TYPE;
drop table SS_OK_DEGREE;
drop table SS_OK_DEPARTMENT;
drop table SS_OK_DEPARTMENT_TYPE; 
drop table SS_OK_DISTR; 
drop table SS_OK_EDUCATION; 
drop table SS_OK_EDUCATION_TITLE; 
drop table SS_OK_ELECTION;
drop table SS_OK_FAMILY_STATUS; 
drop table SS_OK_FITNESS_ARMY;
drop table SS_OK_GENDER;
drop table SS_OK_HOSPITAL;
drop table SS_OK_INCREASE;
drop table SS_OK_INSTITUTION; 
drop table SS_OK_KV_KURS; 
drop table SS_OK_LANGUAGE;
drop table SS_OK_LEAVE; 
drop table SS_OK_LEVEL_BOSS;
drop table SS_OK_LEVEL_DEPARTMENT;
drop table SS_OK_LEVEL_LANGUAGE;
drop table SS_OK_MILITARY_RANK; 
drop table SS_OK_MIN_ZP;
drop table SS_OK_MOTIVE_DISMISSIAL; 
drop table SS_OK_NATIONALITY; 
drop table SS_OK_NCI; 
drop table SS_OK_ORG_BUSINESS_VOYAGE; 
drop table SS_OK_PARTY; 
drop table SS_OK_PASSPORT_TYPE; 
drop table SS_OK_PENALTY; 
drop table SS_OK_PERS_COL_DFLT; 
drop table SS_OK_PERS_QUERY;
drop table SS_OK_PERS_QUERY_COL;
drop table SS_OK_POST;
drop table SS_OK_PRIVILEGE; 
drop table SS_OK_PROFMEMBER;
drop table SS_OK_QUALIFICATION; 
drop table SS_OK_REGION;
drop table SS_OK_REGPLACE;
drop table SS_OK_REG_TYPE;
drop table SS_OK_RELATION;
drop table SS_OK_REZERV;
drop table SS_OK_REZERVE; 
drop table SS_OK_SPECIAL; 
drop table SS_OK_STAFF; 
drop table SS_OK_STATUS;
drop table SS_OK_STR; 
drop table SS_OK_TEMPLATE_COMMAND;
drop table SS_OK_THEME_BUSINESS_VOYAGE; 
drop table SS_OK_TYPE_FORCE;
drop table SS_OK_TYPE_PERIOD; 
drop table SS_OK_VACANCY; 
drop table SS_OK_YOUTH; 
drop table SS_OK_ZP_RATE; 
drop table SS_OK_ZP_RATE_TYPE;

spool off;
