CREATE OR REPLACE TRIGGER TR_OK_AWARD_HIST_DEL
 BEFORE
 DELETE
 ON OK_AWARD
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
declare
 Version constant char(12) := '#~09032012~#';
BEGIN
-- 09_003
  if deleting then
    insert into OK_AWARD_HIST_DEL (
ID,
BRANCH,
PERSONAL_CODE,
AWARD_DATE,
AWARD_INFO,
EMP_CODE,
INS_DATE,
AWARD_DATE_MM,
AWARD_DATE_DD
)
select
:OLD.ID,
:OLD.BRANCH,
:OLD.PERSONAL_CODE,
:OLD.AWARD_DATE,
:OLD.AWARD_INFO,
:OLD.EMP_CODE,
:OLD.INS_DATE,
:OLD.AWARD_DATE_MM,
:OLD.AWARD_DATE_DD
from dual;
  end if;
END;
/
