CREATE OR REPLACE TRIGGER TR_OK_EDUCATION_HIST_DEL
 BEFORE
 DELETE
 ON OK_EDUCATION
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
declare
 Version constant char(12) := '#~09032012~#';
BEGIN
-- 09_003
  if deleting then
    insert into OK_EDUCATION_HIST_DEL (
ID,
BRANCH,
PERSONAL_CODE,
EDUCATION_CODE,
BASIS_CODE,
INSTITUTION_CODE,
BEGIN_DATE,
END_DATE,
PROFESSION_PERSONAL,
QUALIFICATION_CODE,
DIPLOM_NUM,
EMP_CODE,
INS_DATE,
COD_VUZ_PRIM,
CURS,
FAKULTET,
NOSTRA,
NOSTRA_SERIES,
NOSTRA_NUMBER,
NOSTRA_DATE,
DIPLOM_DATE,
BEGIN_DATE_MM,
BEGIN_DATE_DD,
END_DATE_MM,
END_DATE_DD,
EDUCATION_END,
EDUCATION_CITY,
EDUCATION_COUNT_CODE,
VID_EDUCATION_CODE
)
select
:OLD.ID, 
:OLD.BRANCH, 
:OLD.PERSONAL_CODE, 
:OLD.EDUCATION_CODE, 
:OLD.BASIS_CODE, 
:OLD.INSTITUTION_CODE, 
:OLD.BEGIN_DATE, 
:OLD.END_DATE, 
:OLD.PROFESSION_PERSONAL, 
:OLD.QUALIFICATION_CODE, 
:OLD.DIPLOM_NUM, 
:OLD.EMP_CODE, 
:OLD.INS_DATE, 
:OLD.COD_VUZ_PRIM, 
:OLD.CURS, 
:OLD.FAKULTET, 
:OLD.NOSTRA, 
:OLD.NOSTRA_SERIES, 
:OLD.NOSTRA_NUMBER, 
:OLD.NOSTRA_DATE, 
:OLD.DIPLOM_DATE, 
:OLD.BEGIN_DATE_MM, 
:OLD.BEGIN_DATE_DD, 
:OLD.END_DATE_MM, 
:OLD.END_DATE_DD, 
:OLD.EDUCATION_END, 
:OLD.EDUCATION_CITY, 
:OLD.EDUCATION_COUNT_CODE, 
:OLD.VID_EDUCATION_CODE
from dual;
  end if;
END;
/
