CREATE OR REPLACE TRIGGER TR_OK_ELECTION_HIST_DEL
 BEFORE
 DELETE
 ON OK_ELECTION
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
declare
 Version constant char(12) := '#~09032012~#';
BEGIN
-- 09_003
  if deleting then
    insert into OK_ELECTION_HIST_DEL (
ID, 
BRANCH, 
PERSONAL_CODE, 
ELECTION_CODE, 
ELECTION_POST, 
ELECTION_DATE_BEGIN, 
ELECTION_DATE_END, 
EMP_CODE, 
INS_DATE, 
ELECTION_ADDRESS, 
ELECTION_NAME, 
ELECTION_DATE_BEGIN_MM, 
ELECTION_DATE_BEGIN_DD, 
ELECTION_DATE_END_MM, 
ELECTION_DATE_END_DD    
)
select 
:OLD.ID, 
:OLD.BRANCH, 
:OLD.PERSONAL_CODE, 
:OLD.ELECTION_CODE, 
:OLD.ELECTION_POST, 
:OLD.ELECTION_DATE_BEGIN, 
:OLD.ELECTION_DATE_END, 
:OLD.EMP_CODE, 
:OLD.INS_DATE, 
:OLD.ELECTION_ADDRESS, 
:OLD.ELECTION_NAME, 
:OLD.ELECTION_DATE_BEGIN_MM, 
:OLD.ELECTION_DATE_BEGIN_DD, 
:OLD.ELECTION_DATE_END_MM, 
:OLD.ELECTION_DATE_END_DD
from dual;
  end if;
END;
/
