CREATE OR REPLACE TRIGGER TR_OK_LANGUAGE_HIST_DEL
 BEFORE
 DELETE
 ON OK_LANGUAGE
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
declare
 Version constant char(12) := '#~09032012~#';
BEGIN
-- 09_003
  if deleting then
    insert into OK_LANGUAGE_HIST_DEL (
ID,
BRANCH,
PERSONAL_CODE,
LANGUAGE_CODE,
LEVEL_CODE,
EMP_CODE,
INS_DATE,
STATE,
COD_LANG_PRIM
)
select
:OLD.ID,
:OLD.BRANCH,
:OLD.PERSONAL_CODE,
:OLD.LANGUAGE_CODE,
:OLD.LEVEL_CODE,
:OLD.EMP_CODE,
:OLD.INS_DATE,
:OLD.STATE,
:OLD.COD_LANG_PRIM
from dual;
  end if;
END;
/
