
@@TR_DOSTUP_SS_OK_T_B_VOYAGE.sql
@@TR_DOSTUP_SS_OK_TEMPLATE_COMMAND.sql
@@TR_DOSTUP_SS_OK_ORG_BUSINESS_VOYAGE.sql
@@TR_DOSTUP_SS_OK_MOTIVE_DISMISSIAL.sql
@@TR_DOSTUP_SS_OK_LEVEL_DEPARTMENT.sql
@@TR_DOSTUP_SS_OK_EDUCATION_TITLE.sql
@@TR_DOSTUP_SS_OK_EDUCATION_COUNT.sql
@@TR_DOSTUP_SS_OK_DEPARTMENT_TYPE.sql
