spool c:\dep974.txt
alter trigger TR_DOSTUP_SS_OK_DEPARTMENT disable;
update ss_ok_department set department_name='Рахбарият' where department_code=1;
update ss_ok_department set department_name='Ички аудит департаменти' where department_code=2;
update ss_ok_department set department_name='Режавий тафтиш ва банк амалиётларининг аудити бошкармаси ' where department_code=3;
update ss_ok_department set department_name='Тобеъ корхоналарнинг фаолиятини тахлил килиш булими' where department_code=4;
update ss_ok_department set department_name='МХХС буйича молиявий хисоботни кайта куриш булими' where department_code=5;
update ss_ok_department set department_name='Ички назорат департаменти ' where department_code=6;
update ss_ok_department set department_name='Юридик хизмат департаменти' where department_code=7;
update ss_ok_department set department_name='Банк хавфсизлиги департаменти' where department_code=8;
update ss_ok_department set department_name='Хавфсизлик булими' where department_code=9;
update ss_ok_department set department_name='Тахлил булими' where department_code=10;
update ss_ok_department set department_name='Ахборот хавфсизлиги булими ' where department_code=11;
update ss_ok_department set department_name='Ходимлар билан ишлаш департаменти' where department_code=12;
update ss_ok_department set department_name='Ходимларни бахолаш ва ривожлантириш булими' where department_code=13;
update ss_ok_department set department_name='Кадрлар булими' where department_code=14;
update ss_ok_department set department_name='Бухгалтерия хисоби ва хисоботи департаменти' where department_code=15;
update ss_ok_department set department_name='Маъмурий-бошкарув харажатлари булими ' where department_code=16;
update ss_ok_department set department_name='Банклараро хисоблар амалиёти булими' where department_code=17;
update ss_ok_department set department_name='Жамлаш ва хисобот булими' where department_code=18;
update ss_ok_department set department_name='Архив ишларини юритиш булими' where department_code=19;
update ss_ok_department set department_name='Газначилик департаменти' where department_code=20;
update ss_ok_department set department_name='Активлар ва пассивларни бошкариш бошкармаси' where department_code=21;
update ss_ok_department set department_name='Пул бозори амалиётлари булими' where department_code=22;
update ss_ok_department set department_name='Филиалларни ривожлантириш бошкармаси' where department_code=23;
update ss_ok_department set department_name='Бюжетни бизнес режалаштириш ва мониторинги булими' where department_code=24;
update ss_ok_department set department_name='Молиявий хисобот булими' where department_code=25;
update ss_ok_department set department_name='Котибият' where department_code=26;
update ss_ok_department set department_name='Кимматли когозлар департаменти' where department_code=27;
update ss_ok_department set department_name='Инвестиция булими' where department_code=28;
update ss_ok_department set department_name='Эмиссия ва биржа амалиётлари булими' where department_code=29;
update ss_ok_department set department_name='Кредитлаштириш департаменти' where department_code=30;
update ss_ok_department set department_name='Узок муддатли кредитлаш бошкармаси' where department_code=31;
update ss_ok_department set department_name='Савдони молиялаштириш бошкармаси' where department_code=32;
update ss_ok_department set department_name='Кредит портфелини мониторинг килиш бошкармаси' where department_code=33;
update ss_ok_department set department_name='Чакана кредитлаш бошкармаси' where department_code=34;
update ss_ok_department set department_name='Микрокредитлаш булими' where department_code=35;
update ss_ok_department set department_name='Банкнинг инвестицион фаолиятини мувофиклаштириш ва мониторинг килиш департаменти' where department_code=36;
update ss_ok_department set department_name='Лизинг амалиётларни ва инвестицион лойихаларни мониторинг килиш бошкармаси' where department_code=37;
update ss_ok_department set department_name='Инвестицион лойихаларни тахлил килиш бошкармаси' where department_code=38;
update ss_ok_department set department_name='Иктисодий ночор корхоналарни согломлаштириш бошкармаси' where department_code=39;
update ss_ok_department set department_name='Ахборот технологиялари департаменти' where department_code=40;
update ss_ok_department set department_name='Пластик карталарни ривожлантириш бошкармаси ' where department_code=41;
update ss_ok_department set department_name='Программа таъминоти бошкармаси' where department_code=42;
update ss_ok_department set department_name='Коммуникация булими' where department_code=43;
update ss_ok_department set department_name='Методология ва назорат булими' where department_code=44;
update ss_ok_department set department_name='Фойдаланувчиларни куллаб-кувватлаш булими' where department_code=45;
update ss_ok_department set department_name='Бизнесни техник таъминлаш булими' where department_code=46;
update ss_ok_department set department_name='Пул муомаласи бошкармаси' where department_code=47;
update ss_ok_department set department_name='Корпоратив мижозлар булими' where department_code=48;
update ss_ok_department set department_name='Накд пул маблаглари берилишини мониторинг килиш бошкармаси ' where department_code=49;
update ss_ok_department set department_name='Чакана бизнесни ривожлантириш департаменти' where department_code=50;
update ss_ok_department set department_name='Бизнесни ривожлантириш булими' where department_code=51;
update ss_ok_department set department_name='Методология ва хисобот булими' where department_code=52;
update ss_ok_department set department_name='Омонатлар амалиётлари булими' where department_code=53;
update ss_ok_department set department_name='Халкаро пул утказмалари булими' where department_code=54;
update ss_ok_department set department_name='Касса ишлари департаменти' where department_code=55;
update ss_ok_department set department_name='Эмиссия-касса амалиётлари булими' where department_code=56;
update ss_ok_department set department_name='Валюта айирбошлаш амалиётларинининг ихтисослаштирилган бошкармаси ' where department_code=57;
update ss_ok_department set department_name='Ташки иктисодий фаолият ва валюта амалиётлари департаменти' where department_code=58;
update ss_ok_department set department_name='Экспорт-импорт ва валюта амалиётлари бошкармаси' where department_code=59;
update ss_ok_department set department_name='Банклараро хисоблар булими' where department_code=60;
update ss_ok_department set department_name='Халкаро муносабат ва маркетинг департаменти' where department_code=61;
update ss_ok_department set department_name='Халкаро молия институтлари билан муносабат бошкармаси' where department_code=62;
update ss_ok_department set department_name='Маркетинг бошкармаси' where department_code=63;
update ss_ok_department set department_name='Девонхона' where department_code=64;
update ss_ok_department set department_name='Call-марказ' where department_code=65;
update ss_ok_department set department_name='Капитал курилиш департаменти' where department_code=66;
update ss_ok_department set department_name='Техник назорат булими' where department_code=67;
update ss_ok_department set department_name='Лойихаларни экспертиза килиш булими' where department_code=68;
update ss_ok_department set department_name='Маъмурий департамент' where department_code=69;
update ss_ok_department set department_name='Мехнатни мухофаза килиш ва фукаролик мудофааси' where department_code=70;
update ss_ok_department set department_name='Инвентарлаш ва омбор хисоби булими' where department_code=71;
update ss_ok_department set department_name='Моддий-техник таъминот булими' where department_code=72;
update ss_ok_department set department_name='Биноларни эксплуатацияси ва техник хизмат курсатиш булими' where department_code=73;
update ss_ok_department set department_name='Биноларга хизмат курсатиш шуъбаси' where department_code=74;
update ss_ok_department set department_name='Биноларни куриклаш шуъбаси' where department_code=75;
update ss_ok_department set department_name='Амалиёт бошкармаси рахбарияти' where department_code=76;
update ss_ok_department set department_name='Бухгалтерия хисоби ва хисоботи булими' where department_code=77;
update ss_ok_department set department_name='Сунги назорат шуъбаси' where department_code=78;
update ss_ok_department set department_name='Корпоратив мижозлар амалиётлари хисоби шуъбаси' where department_code=79;
update ss_ok_department set department_name='Чакана амалиётлар хисоби шуъбаси' where department_code=80;
update ss_ok_department set department_name='Кредитлаш бошкармаси' where department_code=81;
update ss_ok_department set department_name='Корпоратив мижозларни кредитлаш булими' where department_code=82;
update ss_ok_department set department_name='Чакана кредитлаш булими' where department_code=83;
update ss_ok_department set department_name='Мониторинг булими' where department_code=84;
update ss_ok_department set department_name='Валюта амалиётлари бошкармаси' where department_code=85;
update ss_ok_department set department_name='Пул муомаласи бошкармаси' where department_code=86;
update ss_ok_department set department_name='Корпоратив мижозларга хизмат курсатиш булими' where department_code=87;
update ss_ok_department set department_name='"Соликчи" минибанки' where department_code=88;
update ss_ok_department set department_name='"ТАДИ" минибанки' where department_code=89;
update ss_ok_department set department_name='Накд пул маблаглари берилишини мониторинг килиш булими ' where department_code=90;
update ss_ok_department set department_name='Пластик карталар булими' where department_code=91;
update ss_ok_department set department_name='Чакана бизнес булими' where department_code=92;
update ss_ok_department set department_name='"Алмазар" минибанки' where department_code=93;
update ss_ok_department set department_name='"Билайн" минибанки' where department_code=94;
update ss_ok_department set department_name='Касса амалиётлари булими' where department_code=95;
update ss_ok_department set department_name='Касса хизмати шуъбаси' where department_code=96;
update ss_ok_department set department_name='Валюта айирбошлаш амалиётлари шуъбаси ' where department_code=97;
update ss_ok_department set department_name='Автотранспорт булими' where department_code=98;
update ss_ok_department set department_name='Таъминлаш булими' where department_code=99;
update ss_ok_department set department_name='Молиявий менежмент департаменти' where department_code=100;
update ss_ok_department set department_name='Тадкикотлар ва изланмалар департаменти' where department_code=101;
update ss_ok_department set department_name='Менежмент хатари департаменти' where department_code=102;
update ss_ok_department set department_name='Банкнинг инвестицион фаолиятини мувофиклаштириш ва кимматли когозлар ' where department_code=103;
update ss_ok_department set department_name='Чакана бизнес бошкармаси' where department_code=104;
update ss_ok_department set department_name='Филиал тармокларини ривожлантириш бошкармаси' where department_code=105;
update ss_ok_department set department_name='Бюджетни режалаштириш ва назорат килиш булими' where department_code=106;
update ss_ok_department set department_name='Инвестицион портфелни мониторинг килиш ва кимматли когозлар бошкармаси ' where department_code=107;
update ss_ok_department set department_name='Хатарларни бахолаш ва методология булими' where department_code=108;
update ss_ok_department set department_name='Аффиллир шахслар билан ишлаш булими' where department_code=109;
update ss_ok_department set department_name='Пластик карталар департаменти' where department_code=110;
update ss_ok_department set department_name='Утган даврда бушаганлар булими' where department_code=111;
update ss_ok_department set department_name='"Dolores" минибанки' where department_code=112;
update ss_ok_department set department_name='Маркетинг булими' where department_code=113;
update ss_ok_department set department_name='Халкаро муносабат булими' where department_code=114;
update ss_ok_department set department_name='Пул муомаласи ва касса ишлари департаменти' where department_code=115;
update ss_ok_department set department_name='Юридик хизмат булими' where department_code=116;
update ss_ok_department set department_name='Маъмурий-бошкарув харажатлари ва банклараро амалиётлар хисоби булими ' where department_code=117;
update ss_ok_department set department_name='Муаммоли активлар билан хукукий ишлаш департаменти' where department_code=118;
update ss_ok_department set department_name='Маркетинг ва бизнесни ривожлантириш департаменти' where department_code=119;
update ss_ok_department set department_name='Банк хавфсизлиги булими' where department_code=120;
update ss_ok_department set department_name='Чакана бизнес департаменти' where department_code=121;
update ss_ok_department set department_name='Бизнесни ривожлантириш ва сотув бошкармаси' where department_code=122;
update ss_ok_department set department_name='Бизнесни кузатиш бошкармаси' where department_code=123;
update ss_ok_department set department_name='Сотувни кузатиш шуъбаси' where department_code=124;
update ss_ok_department set department_name='Микрокредитлаш бошкармаси' where department_code=125;
update ss_ok_department set department_name='Молиялаштириш бошкармаси' where department_code=126;
update ss_ok_department set department_name='Банкнинг инвестицион фаолияти департаменти' where department_code=127;
update ss_ok_department set department_name='Кимматли когозлар бошкармаси' where department_code=128;
update ss_ok_department set department_name='Методология бошкармаси' where department_code=129;
update ss_ok_department set department_name='Методология булими' where department_code=130;
update ss_ok_department set department_name='Хукукий экспертиза булими' where department_code=131;
update ss_ok_department set department_name='Талаб ва даъво ишлари булими' where department_code=132;
update ss_ok_department set department_name='Инвестицион лойихалар тахлили булими ' where department_code=133;
update ss_ok_department set department_name='Ходимлар билан ишлаш булими' where department_code=134;
update ss_ok_department set department_name='Режавий тафтиш булими' where department_code=135;
update ss_ok_department set department_name='Бизнес жараённи оптималлаштириш булими' where department_code=136;
update ss_ok_department set department_name='Чакана кредитлаш департаменти' where department_code=137;
update ss_ok_department set department_name='Марказий амалиёт булими рахбарияти' where department_code=138;
update ss_ok_department set department_name='Валюта амалиётлари булими' where department_code=139;
update ss_ok_department set department_name='Кредит амалиётларини мониторинг килиш департаменти' where department_code=140;
update ss_ok_department set department_name='Хисобот булими' where department_code=141;
update ss_ok_department set department_name='Корпоратив кредитлаш департаменти' where department_code=142;
update ss_ok_department set department_name='Пул муомаласи булими' where department_code=143;
update ss_ok_department set department_name='Корпоратив мижозларга хизмат шуъбаси' where department_code=144;
update ss_ok_department set department_name='Корпоратив кредитлаш булими' where department_code=145;
update ss_ok_department set department_name='Касса хизмати булими' where department_code=146;
update ss_ok_department set department_name='Методология ва тадбик килиш бошкармаси' where department_code=147;
update ss_ok_department set department_name='Кредит амалиётларини мониторинг килиш булими' where department_code=148;
update ss_ok_department set department_name='Банк кучмас мулкини амалга ошириш булими ' where department_code=149;
update ss_ok_department set department_name='Мониторинг булими' where department_code=150;
update ss_ok_department set department_name='Корпоратив ва чакана амалиётлар хисоби шуъбаси' where department_code=151;
update ss_ok_department set department_name='Инвестицион активларни бошкариш булими ' where department_code=152;
update ss_ok_department set department_name='Инвестицион активлар бошкармаси' where department_code=153;
update ss_ok_department set department_name='Янги хизматларни тадбик этиш бошкармаси' where department_code=154;
update ss_ok_department set department_name='Накд пул маблагларини мониторинг килиш шуъбаси' where department_code=155;
update ss_ok_department set department_name='Касса ишлари департаменти' where department_code=156;
update ss_ok_department set department_name='Корпоратив бизнес ва маркетинг департаменти' where department_code=157;
update ss_ok_department set department_name='Корпоратив мижозлар билан ишлаш булими' where department_code=158;
update ss_ok_department set department_name='Методология ва котибият булими' where department_code=159;
update ss_ok_department set department_name='Ходимлар билан ишлаш департаменти' where department_code=160;
update ss_ok_department set department_name='Ходимларни бахолаш ва ривожлантириш бошкармаси' where department_code=161;
update ss_ok_department set department_name='Иктисодий тахлил ва молиявий менежмент департаменти' where department_code=162;
update ss_ok_department set department_name='Ижро интизоми ва котибият булими' where department_code=163;
update ss_ok_department set department_name='Касса ишлари ва валюта айирбошлаш амалиётлари департаменти' where department_code=164;
update ss_ok_department set department_name='Бюджетни режалаштириш ва назорат килиш булими' where department_code=165;
update ss_ok_department set department_name='"Ахмад-Дониш" минибанки' where department_code=166;
update ss_ok_department set department_name='Сотувни куллаб-кувватлаш булими' where department_code=167;
update ss_ok_department set department_name='Кредитлаш методологияси бошкармаси' where department_code=168;
update ss_ok_department set department_name='Корпоратив кредитлаш бошкармаси' where department_code=169;
update ss_ok_department set department_name='Филиал тармокларини ривожлантириш булими' where department_code=170;
update ss_ok_department set department_name='Хатарларни бахолаш ва методология булими' where department_code=171;
update ss_ok_department set department_name='Ходимлар билан ишлаш булими' where department_code=172;
update ss_ok_department set department_name='Халкаро тулов тизими булими' where department_code=173;
update ss_ok_department set department_name='Муаммоли кредитлар билан ишлаш ва мониторинг бошкармаси' where department_code=174;
update ss_ok_department set department_name='Омонатчиларнинг маблагларини ва кредиторларни мониторинг килиш бошкармаси' where department_code=175;
update ss_ok_department set department_name='Муаммоли активлар билан ишлаш бошкармаси' where department_code=176;
update ss_ok_department set department_name='Муаммоли активларни мониторинг ва тахлил килиш булими' where department_code=177;
update ss_ok_department set department_name='Муаммоли активлар билан хукукий ишлаш булими' where department_code=178;
update ss_ok_department set department_name='Конверсия амалиётлари булими' where department_code=179;
update ss_ok_department set department_name='Конверсия ва касса ишлари департаменти' where department_code=180;
update ss_ok_department set department_name='Валюта айирбошлаш амалиётлари махсус бошкармаси' where department_code=181;
update ss_ok_department set department_name='Корпоратив бизнес департаменти' where department_code=182;
update ss_ok_department set department_name='Инвестицион лойихалар ва активлар бошкармаси' where department_code=183;
update ss_ok_department set department_name='Шуъба ва тобеъ корхоналар активлари бошкармаси' where department_code=184;
update ss_ok_department set department_name='Омонатчиларнинг маблагларини мониторинг килиш булими' where department_code=185;
update ss_ok_department set department_name='Ходимларни малакасини ошириш ва захирасини тайёрлаш булими' where department_code=186;
update ss_ok_department set department_name='Мижозлар билан ишлаш булими' where department_code=187;
update ss_ok_department set department_name='Конверсия ва валюта айирбошлаш амалиётлари махсус бошкармаси' where department_code=190;
update ss_ok_department set department_name='Капитал курилиш бошкармаси' where department_code=191;
update ss_ok_department set department_name='Банклараро хисоблар булими' where department_code=192;
update ss_ok_department set department_name='пластик карталар шуъбаси' where department_code=2093;
update ss_ok_department set department_name='Рахбарият ' where department_code=2000;
update ss_ok_department set department_name='Ички назорат булими' where department_code=2001;
update ss_ok_department set department_name='Активлар ва пассивларни бошкариш шуъбаси' where department_code=2002;
update ss_ok_department set department_name='Ходимлар билан ишлаш булими' where department_code=2003;
update ss_ok_department set department_name='Банк хавфсизлиги булими' where department_code=2004;
update ss_ok_department set department_name='Ахборот технологиялар булими' where department_code=2005;
update ss_ok_department set department_name='Девонхона' where department_code=2006;
update ss_ok_department set department_name='Бухгалтерия хисоби ва хисоботи булими' where department_code=2007;
update ss_ok_department set department_name='маъмурий-бошкарув харажатлари шуъбаси' where department_code=2008;
update ss_ok_department set department_name='Корпоратив ва чакана амалиётлар хисоби шуъбаси' where department_code=2009;
update ss_ok_department set department_name='Сунги назорат шуъбаси' where department_code=2010;
update ss_ok_department set department_name='Пул муомаласи булими' where department_code=2011;
update ss_ok_department set department_name='Корпоратив мижозларга хизмат курсатиш шуъбаси' where department_code=2012;
update ss_ok_department set department_name='Накд пул маблаглари беришни мониторинг килиш шуъбаси' where department_code=2013;
update ss_ok_department set department_name='Пластик карталар шуъбаси' where department_code=2014;
update ss_ok_department set department_name='Чакана бизнес шуъбаси' where department_code=2015;
update ss_ok_department set department_name='"Регистон" минибанки' where department_code=2016;
update ss_ok_department set department_name='"Микрарайон" минибанки' where department_code=2017;
update ss_ok_department set department_name='"Термез-Дустлик" минибанки' where department_code=2018;
update ss_ok_department set department_name='"Денов" минибанки' where department_code=2019;
update ss_ok_department set department_name='"Бойсун" минибанки' where department_code=2020;
update ss_ok_department set department_name='"Термез-Сурхан" минибанки' where department_code=2021;
update ss_ok_department set department_name='"Термез-Универсал" минибанки' where department_code=2022;
update ss_ok_department set department_name='"Айдын Жол"  минибанки' where department_code=2023;
update ss_ok_department set department_name='"Турткуль" минибанки' where department_code=2024;
update ss_ok_department set department_name='"Турткуль-Марказ" минибанки' where department_code=2025;
update ss_ok_department set department_name='"Мангит" минибанки' where department_code=2026;
update ss_ok_department set department_name='"Беруний" минибанки' where department_code=2027;
update ss_ok_department set department_name='"Фергана" минибанки' where department_code=2028;
update ss_ok_department set department_name='"Фергана-Сарбон"  минибанки' where department_code=2029;
update ss_ok_department set department_name='"Маргилан" минибанки' where department_code=2030;
update ss_ok_department set department_name='"Коканд" минибанки' where department_code=2031;
update ss_ok_department set department_name='"Коканд-Амир-Тимур" минибанки' where department_code=2032;
update ss_ok_department set department_name='"Коканд-Янги-Бозор" минибанки' where department_code=2033;
update ss_ok_department set department_name='"Кува" минибанки' where department_code=2034;
update ss_ok_department set department_name='"Риштан" минибанки' where department_code=2035;
update ss_ok_department set department_name='"Нуравшан" минибанки' where department_code=2036;
update ss_ok_department set department_name='"Алты-Арык" минибанки' where department_code=2037;
update ss_ok_department set department_name='Валюта амалиётлари булими' where department_code=2038;
update ss_ok_department set department_name='Кредитлаш булими' where department_code=2039;
update ss_ok_department set department_name='Корпоратив мижозларни кредитлаш шуъбаси' where department_code=2040;
update ss_ok_department set department_name='Чакана кредитлаш шуъбаси' where department_code=2041;
update ss_ok_department set department_name='Касса хизмати булими' where department_code=2042;
update ss_ok_department set department_name='Валюта айирбошлаш амалиётлари шуъбаси' where department_code=2043;
update ss_ok_department set department_name='Маъмурий булим' where department_code=2044;
update ss_ok_department set department_name='Чакана бизнес булими' where department_code=2045;
update ss_ok_department set department_name='"Ургут" минибанки' where department_code=2046;
update ss_ok_department set department_name='"Каттакурган" минибанки' where department_code=2047;
update ss_ok_department set department_name='"Джума" минибанки' where department_code=2048;
update ss_ok_department set department_name='"Каримбек WU" минибанки' where department_code=2049;
update ss_ok_department set department_name='"Ходжа Ахрора Вали" минибанки' where department_code=2050;
update ss_ok_department set department_name='"Пенджикентская" минибанки' where department_code=2051;
update ss_ok_department set department_name='"Крытый рынок" минибанки' where department_code=2052;
update ss_ok_department set department_name='"Турткуль-Янги бозор" минибанки' where department_code=2053;
update ss_ok_department set department_name='"Дагбитская" минибанки' where department_code=2054;
update ss_ok_department set department_name='"Айритом" минибанки' where department_code=2055;
update ss_ok_department set department_name='Сотувни кузатиш шуъбаси' where department_code=2056;
update ss_ok_department set department_name='"Вокзал" минибанки' where department_code=2057;
update ss_ok_department set department_name='"Вобкент" минибанки' where department_code=2058;
update ss_ok_department set department_name='"Жондор" минибанки' where department_code=2059;
update ss_ok_department set department_name='"Бухара-Самоний" минибанки' where department_code=2060;
update ss_ok_department set department_name='"Бухара-Карвон" минибанки' where department_code=2061;
update ss_ok_department set department_name='"Бухара-Дилкушо" минибанки' where department_code=2062;
update ss_ok_department set department_name='Чакана кредитлаш булими' where department_code=2063;
update ss_ok_department set department_name='Корпоратив кредитлаш булими' where department_code=2064;
update ss_ok_department set department_name='Кредит амалиётларини мониторинг килиш булими' where department_code=2065;
update ss_ok_department set department_name='Мижозлар билан ишлаш булими' where department_code=2066;
update ss_ok_department set department_name='"Ромитан" минибанки' where department_code=2067;
update ss_ok_department set department_name='"Дустлик" минибанки' where department_code=2068;
update ss_ok_department set department_name='"Фазо" минибанки' where department_code=2069;
update ss_ok_department set department_name='"Давлатобод" минибанки' where department_code=2070;
update ss_ok_department set department_name='"Чорсу" минибанки' where department_code=2071;
update ss_ok_department set department_name='"Хазора" минибанки' where department_code=2072;
update ss_ok_department set department_name='"Центральный" минибанки' where department_code=2073;
update ss_ok_department set department_name='Корпоратив мижозларга хизмат курсатиш булими' where department_code=2074;
update ss_ok_department set department_name='"Коканд химик" минибанки' where department_code=2075;
update ss_ok_department set department_name='"Лола" минибанки' where department_code=2076;
update ss_ok_department set department_name='"Сардоба" минибанки' where department_code=2077;
update ss_ok_department set department_name='"Северный" минибанки' where department_code=2078;
update ss_ok_department set department_name='Ходимлар билан ишлаш булими' where department_code=2079;
update ss_ok_department set department_name='"Тукимачи" минибанки' where department_code=2080;
update ss_ok_department set department_name='"Фергана-Нурафшон" минибанки' where department_code=2081;
update ss_ok_department set department_name='"Турон" минибанки' where department_code=2082;
update ss_ok_department set department_name='"Гиждуван" минибанки' where department_code=2083;
update ss_ok_department set department_name='"Каракуль" минибанки' where department_code=2084;
update ss_ok_department set department_name='"Янги Маргилон" минибанки' where department_code=2085;
update ss_ok_department set department_name='"Чупонота" минибанки' where department_code=2086;
update ss_ok_department set department_name='Пластик карталар булими' where department_code=2087;
update ss_ok_department set department_name='"Фергана-Бунедкор" минибанки' where department_code=2088;
update ss_ok_department set department_name='"Андижан" минибанки' where department_code=2089;
update ss_ok_department set department_name='"Термез-Терминал" минибанки' where department_code=2090;
update ss_ok_department set department_name='"Ляби-Хавуз" минибанки' where department_code=2091;
update ss_ok_department set department_name='"Ляби-Хауз" минибанки' where department_code=2092;
update ss_ok_department set department_name='Рахбарият  ' where department_code=3000;
update ss_ok_department set department_name='Ички назорат булими' where department_code=3001;
update ss_ok_department set department_name='Активлар ва пассивларни бошкариш шуъбаси' where department_code=3002;
update ss_ok_department set department_name='Ходимлар билан ишлаш булими' where department_code=3003;
update ss_ok_department set department_name='Банк хавфсизлиги булими' where department_code=3004;
update ss_ok_department set department_name='Ахборот технологиялари булими' where department_code=3005;
update ss_ok_department set department_name='Девонхона' where department_code=3006;
update ss_ok_department set department_name='Бухгалтерия хисоби ва хисоботи булими' where department_code=3007;
update ss_ok_department set department_name='Маъмурий-бошкарув харажатлари шуъбаси' where department_code=3008;
update ss_ok_department set department_name='Корпоратив ва чакана амалиётлар хисоби шуъбаси' where department_code=3009;
update ss_ok_department set department_name='Сунги назорат шуъбаси' where department_code=3010;
update ss_ok_department set department_name='Пул муомаласи булими' where department_code=3011;
update ss_ok_department set department_name='Корпоратив мижозларга хизмат курсатиш шуъбаси' where department_code=3012;
update ss_ok_department set department_name='Накд пул маблаглари беришни мониторинг килиш шуъбаси' where department_code=3013;
update ss_ok_department set department_name='Пластик карталар шуъбаси' where department_code=3014;
update ss_ok_department set department_name='Чакана бизнес шуъбаси' where department_code=3015;
update ss_ok_department set department_name='"Аския" минибанки' where department_code=3016;
update ss_ok_department set department_name='"Шухрат" минибанки' where department_code=3017;
update ss_ok_department set department_name='"Чиланзар" минибанки' where department_code=3018;
update ss_ok_department set department_name='"Саракуль" минибанки' where department_code=3019;
update ss_ok_department set department_name='"Фархадский" минибанки' where department_code=3020;
update ss_ok_department set department_name='"Сергели" минибанки' where department_code=3021;
update ss_ok_department set department_name='"Сабир Рахимов" минибанки' where department_code=3022;
update ss_ok_department set department_name='"Алгоритм" минибанки' where department_code=3023;
update ss_ok_department set department_name='"Кадышева" минибанки' where department_code=3024;
update ss_ok_department set department_name='"Художественный" минибанки' where department_code=3025;
update ss_ok_department set department_name='"Саехат" минибанки' where department_code=3026;
update ss_ok_department set department_name='"Куйлюк" минибанки' where department_code=3027;
update ss_ok_department set department_name='"Куйлюк-Фаргона йули" минибанки' where department_code=3028;
update ss_ok_department set department_name='"ТТЗ" минибанки' where department_code=3029;
update ss_ok_department set department_name='"Юнусабад" минибанки' where department_code=3030;
update ss_ok_department set department_name='"Навои" минибанки' where department_code=3031;
update ss_ok_department set department_name='"Катартал" минибанки' where department_code=3032;
update ss_ok_department set department_name='"Хувайдо" минибанки' where department_code=3033;
update ss_ok_department set department_name='Кредитлаштириш булими' where department_code=3034;
update ss_ok_department set department_name='Корпоратив мижозларни кредитлаш шуъбаси' where department_code=3035;
update ss_ok_department set department_name='Чакана кредитлаш шуъбаси' where department_code=3036;
update ss_ok_department set department_name='Валюта амалиётлари булими' where department_code=3037;
update ss_ok_department set department_name='Касса хизмати булими' where department_code=3038;
update ss_ok_department set department_name='Валюта айирбошлаш амалиётлари шуъбаси' where department_code=3039;
update ss_ok_department set department_name='Маъмурий булим' where department_code=3040;
update ss_ok_department set department_name='Чакана бизнес булими' where department_code=3041;
update ss_ok_department set department_name='Сотувни кузатиш шуъбаси' where department_code=3042;
update ss_ok_department set department_name='"Дархон" минибанки' where department_code=3043;
update ss_ok_department set department_name='"Янги Куйлюк" минибанки' where department_code=3044;
update ss_ok_department set department_name='Чакана кредитлаш булими' where department_code=3045;
update ss_ok_department set department_name='Корпоратив кредитлаш булими' where department_code=3046;
update ss_ok_department set department_name='Кредит амалиётларини мониторинг килиш булими ' where department_code=3047;
update ss_ok_department set department_name='Ходимлар билан ишлаш булими' where department_code=3048;
update ss_ok_department set department_name='Юридик хизмат булими' where department_code=3049;
update ss_ok_department set department_name='"Соликчи" минибанки' where department_code=3050;
update ss_ok_department set department_name='"Дустлик" минибанки' where department_code=3051;
update ss_ok_department set department_name='"Фазо" минибанки' where department_code=3052;
update ss_ok_department set department_name='"Давлатобод" минибанки' where department_code=3053;
update ss_ok_department set department_name='"Чорсу" минибанки' where department_code=3054;
update ss_ok_department set department_name='Корпоратив мижозларга хизмат курсатиш булими' where department_code=3055;
update ss_ok_department set department_name='"Автобазар" минибанки' where department_code=3056;
update ss_ok_department set department_name='Ходимлар билан ишлаш булими' where department_code=3057;
update ss_ok_department set department_name='"Magnit" минибанки' where department_code=3058;
update ss_ok_department set department_name='"Артел" минибанки' where department_code=3059;
update ss_ok_department set department_name='"Олмазор" минибанки' where department_code=3060;
update ss_ok_department set department_name='Пластик карталар булими' where department_code=3061;
update ss_ok_department set department_name='Конверсия амалиётлари булими' where department_code=3062;
commit;
alter trigger TR_DOSTUP_SS_OK_DEPARTMENT enable;

spool off;
