spool c:\select01125.txt
set line 500
prompt # проверочный селект
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1348 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1443 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1334 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1335 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 158 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1546 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 862 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1229 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1164 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1400 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1350 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 320 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 810 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 806 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 964 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1156 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1344 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 384 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 995 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1314 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1045 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 239 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 799 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1214 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1349 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 814 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1432 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1091 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 994 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 746 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1403 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1248 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1340 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 966 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 599 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 102 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1113 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 2104 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1475 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 680 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 69 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1205 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 238 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1024 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 892 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1007 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 734 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1391 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1133 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 869 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 649 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1169 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 5 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1453 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1243 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 519 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 296 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1228 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 897 ;
select branch,tabno,family,first_name,patronymic  from ok_personal where branch='01125' and tabno= 1524 ;


spool off;
