spool c:\ok3.txt
set line 1000
set array 5
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_ACADEMIC';  
  desc OK_ACADEMIC                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_ADDINFORM';  
  desc OK_ADDINFORM                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_ARMY';  
  desc OK_ARMY                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_ATTESTATION';  
  desc OK_ATTESTATION                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_AWARD';  
  desc OK_AWARD                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_CHANGE_FIO';  
  desc OK_CHANGE_FIO                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_CONVICTIONS';  
  desc OK_CONVICTIONS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_DEGREE';  
  desc OK_DEGREE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_EDUCATION';  
  desc OK_EDUCATION                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_ELECTION';  
  desc OK_ELECTION                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_HOSPITAL';  
  desc OK_HOSPITAL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_INCREASE';  
  desc OK_INCREASE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_LANGUAGE';  
  desc OK_LANGUAGE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_LEAVE';  
  desc OK_LEAVE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_NSI';  
  desc OK_NSI                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_PARTY';  
  desc OK_PARTY                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_PENALTY';  
  desc OK_PENALTY                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_PERIOD';  
  desc OK_PERIOD                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_PERSONAL';  
  desc OK_PERSONAL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_PHOTO';  
  desc OK_PHOTO                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_POST';  
  desc OK_POST                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       

select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_PREMIUM';  
  desc OK_PREMIUM                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_PRIVILEGE';  
  desc OK_PRIVILEGE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_RELATION';  
  desc OK_RELATION                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_REZERV';  
  desc OK_REZERV                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_REZERV_DETAIL';  
  desc OK_REZERV_DETAIL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_RISE';  
  desc OK_RISE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_SCIENTIFIC';  
  desc OK_SCIENTIFIC                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_SEND_ALL';  
  desc OK_SEND_ALL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_SEND_ALL_IIAS';  
  desc OK_SEND_ALL_IIAS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_STAT';  
  desc OK_STAT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_STAT_SALARY';  
  desc OK_STAT_SALARY                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_TABEL';  
  desc OK_TABEL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_VOYAGE';  
  desc OK_VOYAGE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='OK_YOUTH';  
  desc OK_YOUTH                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     

select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK';  
  desc SS_OK                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_ACADEMIC';  
  desc SS_OK_ACADEMIC                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_ARMY';  
  desc SS_OK_ARMY                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_ARMY_GROUP';  
  desc SS_OK_ARMY_GROUP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_ARTICLE';  
  desc SS_OK_ARTICLE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_BASE_MOVE';  
  desc SS_OK_BASE_MOVE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_BASIS';  
  desc SS_OK_BASIS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_CATEGORY';  
  desc SS_OK_CATEGORY                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_CATEGORY_ARMY';  
  desc SS_OK_CATEGORY_ARMY                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_COMMAND_PARAM';  
  desc SS_OK_COMMAND_PARAM                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_COMMAND_TYPE';  
  desc SS_OK_COMMAND_TYPE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_DEGREE';  
  desc SS_OK_DEGREE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_DEPARTMENT';  
  desc SS_OK_DEPARTMENT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_DEPARTMENT_TYPE';  
  desc SS_OK_DEPARTMENT_TYPE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_EDUCATION';  
  desc SS_OK_EDUCATION                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_EDUCATION_TITLE';  
  desc SS_OK_EDUCATION_TITLE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_ELECTION';  
  desc SS_OK_ELECTION                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_FAMILY_STATUS';  
  desc SS_OK_FAMILY_STATUS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_FITNESS_ARMY';  
  desc SS_OK_FITNESS_ARMY                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_GENDER';  
  desc SS_OK_GENDER                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_HOSPITAL';  
  desc SS_OK_HOSPITAL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_INSTITUTION';  
  desc SS_OK_INSTITUTION                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_LANGUAGE';  
  desc SS_OK_LANGUAGE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_LEAVE';  
  desc SS_OK_LEAVE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_LEVEL_BOSS';  
  desc SS_OK_LEVEL_BOSS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_LEVEL_DEPARTMENT';  
  desc SS_OK_LEVEL_DEPARTMENT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_LEVEL_LANGUAGE';  
  desc SS_OK_LEVEL_LANGUAGE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_MILITARY_RANK';  
  desc SS_OK_MILITARY_RANK                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_MIN_ZP';  
  desc SS_OK_MIN_ZP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_MOTIVE_DISMISSIAL';  
  desc SS_OK_MOTIVE_DISMISSIAL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_NATIONALITY';  
  desc SS_OK_NATIONALITY                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_NCI';  
  desc SS_OK_NCI                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_PARTY';  
  desc SS_OK_PARTY                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_PENALTY';  
  desc SS_OK_PENALTY                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_PERS_COL_DFLT';  
  desc SS_OK_PERS_COL_DFLT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_PERS_QUERY';  
  desc SS_OK_PERS_QUERY                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_PERS_QUERY_COL';  
  desc SS_OK_PERS_QUERY_COL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_POST';  
  desc SS_OK_POST                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_PRIVILEGE';  
  desc SS_OK_PRIVILEGE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_PROFMEMBER';  
  desc SS_OK_PROFMEMBER                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_QUALIFICATION';  
  desc SS_OK_QUALIFICATION                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_REG_TYPE';  
  desc SS_OK_REG_TYPE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_RELATION';  
  desc SS_OK_RELATION                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_REZERV';  
  desc SS_OK_REZERV                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_REZERVE';  
  desc SS_OK_REZERVE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_SPECIAL';  
  desc SS_OK_SPECIAL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_STAFF';  
  desc SS_OK_STAFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_STATUS';  
  desc SS_OK_STATUS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_TEMPLATE_COMMAND';  
  desc SS_OK_TEMPLATE_COMMAND                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_TYPE_FORCE';  
  desc SS_OK_TYPE_FORCE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_TYPE_PERIOD';  
  desc SS_OK_TYPE_PERIOD                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_VACANCY';  
  desc SS_OK_VACANCY                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
select table_name,comments from all_tab_comments where owner='BANK394' and table_name='SS_OK_YOUTH';  
  desc SS_OK_YOUTH                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               

spool off;
