spool c:\post974.txt
update ss_ok_post set post_name='Бошкарув Раиси' where post_code=1;
update ss_ok_post set post_name='Бошкарув Раиси Биринчи Уринбосари' where post_code=2;
update ss_ok_post set post_name='Бошкарув Раиси Уринбосари' where post_code=3;
update ss_ok_post set post_name='Бош бухгалтер' where post_code=4;
update ss_ok_post set post_name='Департамент директори' where post_code=5;
update ss_ok_post set post_name='Филиал бош бухгалтери' where post_code=9;
update ss_ok_post set post_name='Бош бухгалтер уринбосари' where post_code=10;
update ss_ok_post set post_name='Департамент директори уринбосари' where post_code=11;
update ss_ok_post set post_name='Бошкарув Раиси маслахатчиси' where post_code=14;
update ss_ok_post set post_name='Бошкарув Раиси маслахатчиси ' where post_code=15;
update ss_ok_post set post_name='Банк Кенгаши Раиси маслахатчиси' where post_code=17;
update ss_ok_post set post_name='Банк Кенгаши Раиси маслахатчиси ' where post_code=18;
update ss_ok_post set post_name='Бошкарма бошлиги' where post_code=19;
update ss_ok_post set post_name='Филиал бош бухгалтери уринбосари' where post_code=20;
update ss_ok_post set post_name='Бошкарув Раиси ердамчиси' where post_code=21;
update ss_ok_post set post_name='Банк Кенгаши Раиси ердамчиси' where post_code=22;
update ss_ok_post set post_name='Бошкарма бошлиги уринбосари' where post_code=23;
update ss_ok_post set post_name='Булим бошлиги' where post_code=24;
update ss_ok_post set post_name='Касса мудири' where post_code=25;
update ss_ok_post set post_name='Булим бошлиги уринбосари' where post_code=27;
update ss_ok_post set post_name='Шуъба мудири' where post_code=28;
update ss_ok_post set post_name='Минибанк бошлиги' where post_code=29;
update ss_ok_post set post_name='Бош мутахассис' where post_code=30;
update ss_ok_post set post_name='Етакчи мутахассис' where post_code=32;
update ss_ok_post set post_name='1 тоифали мутахассис' where post_code=33;
update ss_ok_post set post_name='1 тоифали кассир' where post_code=34;
update ss_ok_post set post_name='1 тоифали назоратчи' where post_code=35;
update ss_ok_post set post_name='2 тоифали мутахассис' where post_code=36;
update ss_ok_post set post_name='Электрик' where post_code=37;
update ss_ok_post set post_name='Мутахассис' where post_code=38;
update ss_ok_post set post_name='2 тоифали кассир' where post_code=39;
update ss_ok_post set post_name='2 тоифали назоратчи' where post_code=40;
update ss_ok_post set post_name='Катта архивариус' where post_code=41;
update ss_ok_post set post_name='Ховлибон' where post_code=50;
update ss_ok_post set post_name='Коровул' where post_code=52;
update ss_ok_post set post_name='Банкир' where post_code=92;
update ss_ok_post set post_name='Юрисконсульт' where post_code=93;
update ss_ok_post set post_name='Департамент директори-Бошкарув Раиси маслахатчиси' where post_code=94;
update ss_ok_post set post_name='Коровул' where post_code=96;
update ss_ok_post set post_name='Марказий амалиёт булими бошлиги' where post_code=99;
update ss_ok_post set post_name='Энергиячи' where post_code=100;
update ss_ok_post set post_name='Банк Кенгаши котиби' where post_code=103;
update ss_ok_post set post_name='Марказий амалиёт булими бошлиги уринбосари' where post_code=106;
update ss_ok_post set post_name='Департамент директори уринбосари-булим бошлиги' where post_code=108;

update ss_ok_post set post_name='Филиал бошкарувчиси' where post_code=6;
update ss_ok_post set post_name='Филиал бошкарувчиси уринбосари' where post_code=12;
update ss_ok_post set post_name='Юрисконсульт' where post_code=26;
update ss_ok_post set post_name='Филиал бош бухгалтери' where post_code=56;
update ss_ok_post set post_name='Филиал бош бухгалтери уринбосари' where post_code=58;
update ss_ok_post set post_name='Юбулим бошлиги' where post_code=60;
update ss_ok_post set post_name='Касса  мудири' where post_code=62;
update ss_ok_post set post_name='Шуъба мудири' where post_code=65;
update ss_ok_post set post_name='Минибанк бошлиги' where post_code=67;
update ss_ok_post set post_name='Бош мутахассис' where post_code=69;
update ss_ok_post set post_name='Етакчи мутахассис' where post_code=71;
update ss_ok_post set post_name='1 тоифали мутахассис' where post_code=73;
update ss_ok_post set post_name='1 тоифали кассир' where post_code=75;
update ss_ok_post set post_name='1 тоифали назоратчи' where post_code=77;
update ss_ok_post set post_name='2 тоифали мутахассис' where post_code=79;
update ss_ok_post set post_name='Электрик' where post_code=81;
update ss_ok_post set post_name='Мутахассис' where post_code=83;
update ss_ok_post set post_name='2 тоифали кассир' where post_code=85;
update ss_ok_post set post_name='2 тоифали назоратчи' where post_code=87;
update ss_ok_post set post_name='Ховлибон' where post_code=89;
update ss_ok_post set post_name='Богбон' where post_code=91;
update ss_ok_post set post_name='Коровул' where post_code=97;

update ss_ok_post set post_name='Амалиёт бошкармаси бошлиги' where post_code=8;
update ss_ok_post set post_name='Амалиёт бошкармаси бошлиги уринбосари' where post_code=13;
update ss_ok_post set post_name='Энергиячи' where post_code=31;
update ss_ok_post set post_name='Богбон' where post_code=51;
update ss_ok_post set post_name='Филиал бошкарувчиси' where post_code=53;
update ss_ok_post set post_name='Филиал бошкарувчиси уринбосари' where post_code=54;
update ss_ok_post set post_name='Филиал бош бухгалтери ' where post_code=57;
update ss_ok_post set post_name='Филиал бош бухгалтери уринбосари' where post_code=59;
update ss_ok_post set post_name='Булим бошлиги' where post_code=61;
update ss_ok_post set post_name='Касса мудири' where post_code=63;
update ss_ok_post set post_name='Юрисконсульт' where post_code=64;
update ss_ok_post set post_name='Шуъба мудири' where post_code=66;
update ss_ok_post set post_name='Минибанк бошлиги' where post_code=68;
update ss_ok_post set post_name='Бош мутахассис' where post_code=70;
update ss_ok_post set post_name='Етакчи мутахассис' where post_code=72;
update ss_ok_post set post_name='1 тоифали мутахассис' where post_code=74;
update ss_ok_post set post_name='1 тоифали кассир' where post_code=76;
update ss_ok_post set post_name='1 тоифали назоратчи' where post_code=78;
update ss_ok_post set post_name='2 тоифали мутахассис' where post_code=80;
update ss_ok_post set post_name='Электрик' where post_code=82;
update ss_ok_post set post_name='Мутахассис' where post_code=84;
update ss_ok_post set post_name='2 тоифали кассир' where post_code=86;
update ss_ok_post set post_name='2 тоифали назоратчи' where post_code=88;
update ss_ok_post set post_name='Ховлибон' where post_code=90;
update ss_ok_post set post_name='Коровул' where post_code=98;
update ss_ok_post set post_name='Филиал бошкарувчиси маслахатчиси' where post_code=102;
update ss_ok_post set post_name='Катта архивариус' where post_code=105;
update ss_ok_post set post_name='Булим бошлиги уринбосари' where post_code=107;

commit;

spool off;
