-- 17.05.2005

ALTER TABLE OK_RELATION
 MODIFY (
  RELATION_PATRONYMIC NULL
);
ALTER TABLE OK_RELATION
 MODIFY (
  RELATION_BIRTHDAY NULL
);
ALTER TABLE OK_RELATION
 MODIFY (
  RELATION_BIRTHPLACE NULL
);
ALTER TABLE OK_RELATION
 MODIFY (
  RELATION_OFFICE NULL
);
ALTER TABLE OK_RELATION
 MODIFY (
  RELATION_POST NULL
);
ALTER TABLE OK_RELATION
 MODIFY (
  RELATION_HOME_ADDRESS NULL
);
ALTER TABLE OK_RELATION
 MODIFY (
  EMP_CODE NULL
);
ALTER TABLE OK_RELATION
 MODIFY (
  INS_DATE NULL
);
