delete from okedb_appoints;
delete from okedb_appoints_arh;
commit;


delete from OK_ACADEMIC ;
delete from OK_ADDINFORM ;
delete from OK_ARMY ;
delete from OK_ATTESTATION ;
delete from OK_AWARD ;
delete from OK_BUSINESS_VOYAGE ;
delete from OK_CHANGE_FIO ;
delete from OK_CONVICTIONS ;
delete from OK_DEGREE ;
delete from OK_EDUCATION ;
delete from OK_ELECTION ;
delete from OK_HOSPITAL ;
delete from OK_INCREASE ;
delete from OK_KURS ;
delete from OK_LANGUAGE ;
delete from OK_LEAVE ;
delete from OK_PARTY ;
delete from OK_PENALTY ;
delete from OK_PERIOD ;
delete from OK_PERSONAL ;
delete from OK_PHOTO ;
delete from OK_POST ;
delete from OK_PREMIUM ;
delete from OK_PRIVILEGE ;
delete from OK_RELATION ;
delete from OK_REZERV ;
delete from OK_REZERV_DETAIL ;
delete from OK_RISE ;
delete from OK_SCIENTIFIC ;
delete from OK_SEND_ALL ;
delete from OK_SEND_ALL_IIAS ;
delete from OK_TABEL ;
delete from OK_VOYAGE ;
delete from OK_YOUTH ;
delete from OK_ZP_RATE ;
commit;
