CREATE OR REPLACE TRIGGER TR_OK_RISE_HIST_DEL
 BEFORE
 DELETE
 ON OK_RISE
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
declare
 Version constant char(12) := '#~09032012~#';
BEGIN
-- 09_003
  if deleting then
    insert into OK_RISE_HIST_DEL (
ID,
BRANCH,
PERSONAL_CODE,
RISE_DATE_YEAR,
RISE_INFO,
EMP_CODE,
INS_DATE,
RISE_DATE_MM,
RISE_DATE_DD
)
select
:OLD.ID,
:OLD.BRANCH,
:OLD.PERSONAL_CODE,
:OLD.RISE_DATE_YEAR,
:OLD.RISE_INFO,
:OLD.EMP_CODE,
:OLD.INS_DATE,
:OLD.RISE_DATE_MM,
:OLD.RISE_DATE_DD
from dual;
  end if;
END;
/
