CREATE OR REPLACE TRIGGER TR_OK_VOYAGE_HIST_DEL
 BEFORE
 DELETE
 ON OK_VOYAGE
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
declare
 Version constant char(12) := '#~09032012~#';
BEGIN
-- 09_003
  if deleting then
    insert into OK_VOYAGE_HIST_DEL (
ID,
BRANCH,
PERSONAL_CODE,
VOYAGE_DATE,
VOYAGE_LAND,
VOYAGE_INFO,
EMP_CODE,
INS_DATE,
VOYAGE_STR,
DATA_IN,
VOYAGE_DATE_MM,
VOYAGE_DATE_DD,
DATA_IN_MM,
DATA_IN_DD
)
select
:OLD.ID,
:OLD.BRANCH,
:OLD.PERSONAL_CODE,
:OLD.VOYAGE_DATE,
:OLD.VOYAGE_LAND,
:OLD.VOYAGE_INFO,
:OLD.EMP_CODE,
:OLD.INS_DATE,
:OLD.VOYAGE_STR,
:OLD.DATA_IN,
:OLD.VOYAGE_DATE_MM,
:OLD.VOYAGE_DATE_DD,
:OLD.DATA_IN_MM,
:OLD.DATA_IN_DD
from dual;
  end if;
END;
/
